#!/bin/bash

#converts a matches file (generated by extractaligned.java) to a bed file.  Can also specify a string to search for and only return records with that sequence.

NT=$2
FL=$1
if ["$NT" == ""]; then
	grep ">" $FL | sed s/"(-)"/"\tminus"/g | sed s/'-'/"\t"/g | sed s/':'/"\t"/g | sed s/"(+)"/"\t+"/g | sed s/"minus"/"-"/g | sed s/'>'/""/g
else
	grep -B 1 "^${NT}$" $FL | grep ">" | sed s/"(-)"/"\tminus"/g | sed s/'-'/"\t"/g | sed s/':'/"\t"/g | sed s/"(+)"/"\t+"/g | sed s/"minus"/"-"/g | sed s/'>'/""/g
fi

